package dispatch

import "testing"

// Two agents must not share stored state. Keyed by kind alone — which is what
// ComponentInit did — the second agent's build reuses the first's plan
// (including its output directory) and, worse, reads the first's written
// manifest as its own. DecideRebuild's job is to remove files the current plan
// no longer lists, so building `agents/billing` after `agents/shipping` could
// delete shipping's files.
func TestEachInstanceKeysItsOwnState(t *testing.T) {
	billing, shipping := Agent("billing"), Agent("shipping")

	if billing.Key() == shipping.Key() {
		t.Fatalf("both agents key state as %q — one rebuild can delete the other's files", billing.Key())
	}
	// The manifest is the file that decides deletions; it is named from a hash
	// of the key, so distinct keys must produce distinct manifests.
	if manifestName("/t", billing.Key()) == manifestName("/t", shipping.Key()) {
		t.Error("two agents share one written manifest")
	}
	// And their directories are distinct.
	if billing.Dir() == shipping.Dir() {
		t.Errorf("both agents generate into %q", billing.Dir())
	}
}

// A singleton's key must stay the bare kind. Manifests, plans and records on
// disk are keyed by a hash of this string, so changing it for the orchestrator
// would orphan every tenant already generated.
func TestSingletonKeysAreUnchanged(t *testing.T) {
	for _, c := range []Component{Orchestrator(), Gateway()} {
		if c.Key() != c.Kind {
			t.Errorf("%s keys state as %q, want the bare kind — "+
				"every manifest already on disk is found by that name", c.Kind, c.Key())
		}
	}
}

// The directories are the ones the single-shot commands wrote to, so a tenant
// generated by the old path and rebuilt by this one lands in the same place.
func TestDirectoriesMatchTheOnesTheOldPathUsed(t *testing.T) {
	for _, tc := range []struct {
		c    Component
		want string
	}{
		{Orchestrator(), "."},
		{Agent("billing"), "agents/billing"},
		{Domain("logistics"), "domains/logistics"},
		{Gateway(), "gateway"},
	} {
		if got := tc.c.Dir(); got != tc.want {
			t.Errorf("%s writes to %q, want %q — the old command used %q, and a rebuild "+
				"that writes elsewhere abandons what is already there", tc.c.Label(), got, tc.want, tc.want)
		}
	}
}

// A named kind with no name would write into `agents/` and own every agent's
// files. A singleton with a name would key state nothing else can find.
func TestAComponentThatCannotBeBuiltSaysSo(t *testing.T) {
	for _, tc := range []struct {
		name    string
		c       Component
		wantBad bool
	}{
		{"agent without a name", Component{Kind: "agent"}, true},
		{"domain without a name", Component{Kind: "domain"}, true},
		{"orchestrator with a name", Component{Kind: "orchestrator", Name: "x"}, true},
		{"gateway with a name", Component{Kind: "gateway", Name: "x"}, true},
		{"no kind at all", Component{}, true},
		{"a named agent", Agent("billing"), false},
		{"the orchestrator", Orchestrator(), false},
		{"the gateway", Gateway(), false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			bad := tc.c.Valid()
			if tc.wantBad && bad == "" {
				t.Errorf("%+v was accepted", tc.c)
			}
			if !tc.wantBad && bad != "" {
				t.Errorf("%+v was refused: %s", tc.c, bad)
			}
		})
	}
}

// Kind selects the blueprint; the key must never be used for that. Asking for
// a blueprint named `agent:billing` finds nothing.
func TestTheBlueprintIsChosenByKindNotByInstance(t *testing.T) {
	c := Agent("billing")
	if got := targetBlueprint(c.Kind); got == "" {
		t.Fatalf("no blueprint for kind %q", c.Kind)
	}
	if targetBlueprint(c.Key()) == targetBlueprint(c.Kind) && c.Key() != c.Kind {
		t.Error("targetBlueprint answers the same for a key and a kind, so passing the wrong one " +
			"would not be caught here — the distinction is only enforced by the call sites")
	}
	// Every agent is graded against the same assertions, whatever it is called.
	if GenerationRoots(Agent("a").Kind, "go")[2] != GenerationRoots(Agent("b").Kind, "go")[2] {
		t.Error("two agents resolve different blueprint roots")
	}
}
